// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ErrorResponse is an autogenerated mock type for the ErrorResponse type
type ErrorResponse struct {
	mock.Mock
}

type ErrorResponse_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorResponse) EXPECT() *ErrorResponse_Expecter {
	return &ErrorResponse_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: w, r
func (_m *ErrorResponse) Execute(w http.ResponseWriter, r *http.Request) error {
	ret := _m.Called(w, r)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(http.ResponseWriter, *http.Request) error); ok {
		r0 = rf(w, r)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ErrorResponse_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type ErrorResponse_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - w http.ResponseWriter
//   - r *http.Request
func (_e *ErrorResponse_Expecter) Execute(w interface{}, r interface{}) *ErrorResponse_Execute_Call {
	return &ErrorResponse_Execute_Call{Call: _e.mock.On("Execute", w, r)}
}

func (_c *ErrorResponse_Execute_Call) Run(run func(w http.ResponseWriter, r *http.Request)) *ErrorResponse_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(http.ResponseWriter), args[1].(*http.Request))
	})
	return _c
}

func (_c *ErrorResponse_Execute_Call) Return(_a0 error) *ErrorResponse_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ErrorResponse_Execute_Call) RunAndReturn(run func(http.ResponseWriter, *http.Request) error) *ErrorResponse_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewErrorResponse creates a new instance of ErrorResponse. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorResponse(t interface {
	mock.TestingT
	Cleanup(func())
}) *ErrorResponse {
	mock := &ErrorResponse{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
